Add missing Qt includes
    shaderDialog.h:55:21: error: 'QSlider' was not declared in this scope
    shaderDialog.h:56:15: error: 'QLineEdit' was not declared in this scope
    paintbox.cpp:35:30: error: invalid use of incomplete type 'class QAction'
    ...